MATCH_KEYS:
  trainer: OnPolicyTrainer
  storage: [VanillaRolloutStorage]
  distribution: [Categorical, DiagonalGaussian]

DEFAULT_CFGS:
  ####### Train setup
  device: cpu                      # Device (cpu, cuda, ...) on which the code should be run.
  seed: 1                          # Random seed for reproduction.
  pretraining: false               # Turn on the pre-training mode.
  init_model_path:                 # Path of initial model parameters.
  num_train_steps: 25000000        # Number of training steps.
  num_steps: 256                   # Number of the sample length of per rollout.
  ####### Test setup
  test_every_episodes: 10          # Testing interval, only for `on-policy` agents.
  num_test_episodes: 10            # Number of testing episodes.
  ####### Xploit part
  encoder:
    image:
      name: EspeholtResidualEncoder
      feature_dim: 256
    state:
      name: IdentityEncoder
      feature_dim:
  agent:
    name: PPG
  storage:
    name: VanillaRolloutStorage
    batch_size: 2048
  ####### Xplore part
  distribution:
    Discrete: 
      name: Categorical
    Box: 
      name: DiagonalGaussian
  augmentation:
    name:
  reward:
    name: