MATCH_KEYS:
  trainer: OffPolicyTrainer
  storage: [VanillaReplayStorage, PrioritizedReplayStorage]
  distribution: [SquashedNormal]

DEFAULT_CFGS:
  ####### Train setup
  device: cpu                      # Device (cpu, cuda, ...) on which the code should be run.
  seed: 1                          # Random seed for reproduction.
  pretraining: false               # Turn on the pre-training mode.
  init_model_path:                 # Path of initial model parameters.
  num_train_steps: 1000000         # Number of training steps.
  num_init_steps: 2000             # Number of initial exploration steps, only for `off-policy` agents.
  ####### Test setup
  test_every_steps: 5000           # Testing interval, only for `off-policy` agents.
  num_test_episodes: 10            # Number of testing episodes.
  ####### Xploit part
  encoder:
    image:
      name: TassaCnnEncoder
      feature_dim: 50
    state:
      name: IdentityEncoder
      feature_dim:
  agent:
    name: SAC
  storage:
    name: VanillaReplayStorage
    storage_size: 1000000
    batch_size: 1024
  ####### Xplore part
  distribution:
    Box: 
      name: SquashedNormal
  augmentation:
    name: 
  reward:
    name: