from .on_policy_shared_actor_critic import OnPolicySharedActorCritic as OnPolicySharedActorCritic
from .on_policy_decoupled_actor_critic import OnPolicyDecoupledActorCritic as OnPolicyDecoupledActorCritic
from .off_policy_deterministic_actor_double_critic import OffPolicyDeterministicActorDoubleCritic as OffPolicyDeterministicActorDoubleCritic
from .off_policy_stochastic_actor_double_critic import OffPolicyStochasticActorDoubleCritic as OffPolicyStochasticActorDoubleCritic
from .distributed_actor_critic import DistributedActorCritic as DistributedActorCritic

from .on_policy_shared_actor_critic import NpuOnPolicySharedActorCritic as NpuOnPolicySharedActorCritic
from .on_policy_decoupled_actor_critic import NpuOnPolicyDecoupledActorCritic as NpuOnPolicyDecoupledActorCritic
from .off_policy_deterministic_actor_double_critic import NpuOffPolicyDeterministicActorDoubleCritic as NpuOffPolicyDeterministicActorDoubleCritic
from .off_policy_stochastic_actor_double_critic import NpuOffPolicyStochasticActorDoubleCritic as NpuOffPolicyStochasticActorDoubleCritic