from .espeholt_residual_encoder import EspeholtResidualEncoder as EspeholtResidualEncoder
from .identity_encoder import IdentityEncoder as IdentityEncoder
from .mnih_cnn_encoder import MnihCnnEncoder as MnihCnnEncoder
from .pathak_cnn_encoder import PathakCnnEncoder as PathakCnnEncoder
from .tassa_cnn_encoder import TassaCnnEncoder as TassaCnnEncoder
from .vanilla_mlp_encoder import VanillaMlpEncoder as VanillaMlpEncoder
