from .base import BaseAugmentation
from .random_crop import RandomCrop
from .random_shift import RandomShift
from .grayscale import GrayScale
from .random_translate import RandomTranslate
from .random_rotate import RandomRotate
from .random_flip import RandomFlip
from .random_convolution import RandomConvolution
from .random_colorjitter import RandomColorJitter
from .random_cutout import RandomCutout
from .random_cutoutcolor import RandomCutoutColor